import {
  ArrowUpTrayIcon,
  BookOpenIcon,
  BookmarkIcon,
  CheckIcon,
  ChevronUpDownIcon,
  ClipboardDocumentListIcon,
  ViewfinderCircleIcon,
} from "@heroicons/react/20/solid";
import { Link, useNavigate } from "react-router-dom";
import { useAuth } from "../../contexts/UserContext";
import { useEffect } from "react";
import Button from "../../components/ui/Button";

const virtualWardrobeFeatures = [
  {
    name: "Track Pieces",
    description:
      "Keep track of indiviual clothing items so that you always have your wardrobe with you whenever you're out shopping",
    icon: ClipboardDocumentListIcon,
  },
  {
    name: "Upload Images",
    description:
      "Upload and view high quality images of your pieces so you always know what the pieces look like exactly",
    icon: ArrowUpTrayIcon,
  },
  {
    name: "Personal Lookbook",
    description:
      "Create your own lookbook of your favorite outfits so you can free up both time and head space to focus on expressing your most fashionable self",
    icon: BookOpenIcon,
  },
];

const outfitGeneratorFeatures = [
  {
    name: "Pick Your Vibe",
    description:
      "Choose the vibe and style your going for with your preset options. From cozy, cool, monochrome, etc... we have you covered.",
    icon: ViewfinderCircleIcon,
  },
  {
    name: "Choose Pieces",
    description:
      "Have a specific piece you want to wear? Select any number of pieces and the generator will fill the remaining slots with pieces form your wardrobe",
    icon: ChevronUpDownIcon,
  },
  {
    name: "Save The Look",
    description:
      "Like a generated outfit? Save it directly to your lookbook so you always have it with you.",
    icon: BookmarkIcon,
  },
];

const includedFeatures = [
  "Wardrobe Manager",
  "Limited Outfit Generation",
  "Basic Style Insights",
];
const premiumFeatures = [
  "Wardrobe Manager",
  "Unlimited Outfit Generation",
  "Advanced Style Insights",
  "Priority Support",
  "No Ads",
];
const faq = [
  {
    show: false,
    question: "How does Rizmic generate outfits?",
    answer:
      "Our algorithm analyzes your wardrobe, personal style preferences, and the latest fashion trends to create stylish and unique outfit combinations that suit your taste.",
  },
  {
    show: false,
    question: "Can I customize the outfits generated by Rizmic?",
    answer:
      "Yes, you can easily customize the generated outfits by swapping out individual items or adjusting the style parameters to better match your preferences.",
  },
  {
    show: false,
    question: "Is my wardrobe data secure on Rizmic?",
    answer:
      "Your privacy is our top priority. We employ state-of-the-art security measures to protect your data, and we never share your personal information with third parties without your consent.",
  },
  {
    show: false,
    question: "Do you offer a free trial for the Premium Plan?",
    answer:
      "Yes, we offer a 3-day free trial for our Premium Plan, allowing you to explore all the advanced features and benefits without any obligation.",
  },
];

export default function Home() {
  const navigate = useNavigate();
  const { isAuthenticated } = useAuth();
  useEffect(() => {
    if (isAuthenticated) {
      navigate("/wardrobe");
    }
  });
  return (
    <div className="content-container max-w-7xl mx-auto">
      <main className="w-full mx-auto px-4 ">
        <section className="text-center mt-24 flex justify-center items-center py-28">
          <div className="hero-text py-20 flex flex-col items-center justify-center gap-10">
            <div>
              <h1 className="text-5xl font-bold  mb-4 sm:text-7xl">
                Your Personal Wardrobe Manager
              </h1>
              <p className="text-xl text-slategrey max-w-4xl">
                Revolutionize the way you dress with our intuitive app that
                keeps your wardrobe organized and generates stylish outfits
                tailored to your taste.
              </p>
            </div>
            <Button
              onClick={() => navigate("/register")}
              className="text-xl px-6 py-3 font-bold"
            >
              Get Started
            </Button>
          </div>
        </section>

        <section id="features" className="py-24">
          <h2 className="text-4xl font-bold tracking-tight sm:text-6xl">
            Features
          </h2>

          <div className="overflow-hidden py-20">
            <div className=" px-6 lg:px-8">
              <div className="flex items-center justify-center ">
                <div className="lg:pr-8 lg:pt-4">
                  <div className="lg:max-w-2xl">
                    <h2 className="text-base font-semibold leading-7 text-ultramarineBlue">
                      Shop more, think less
                    </h2>
                    <p className="mt-2 text-4xl font-bold tracking-tight text-gray-800 dark:text-gray-100 sm:text-6xl">
                      Virtual Wardrobe
                    </p>
                    <p className="mt-6">
                      Easily catalog your wardrobe, track your most-worn items,
                      and stay organized with our intuitive wardrobe manager.
                    </p>
                    <dl className="mt-10 max-w-xl space-y-8 text-base leading-7 text-gray-600 dark:text-gray-200 lg:max-w-none">
                      {virtualWardrobeFeatures.map((feature) => (
                        <div key={feature.name} className="relative pl-9">
                          <dt className="inline font-semibold text-gray-800 dark:text-gray-100">
                            <feature.icon
                              className="absolute left-1 top-1 h-5 w-5 text-ultramarineBlue"
                              aria-hidden="true"
                            />
                            {feature.name}
                          </dt>{" "}
                          <dd className="inline">{feature.description}</dd>
                        </div>
                      ))}
                    </dl>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="overflow-hidden">
            <div className=" px-6 lg:px-8">
              <div className="flex items-center justify-center ">
                <div className="lg:pr-8 lg:pt-4">
                  <div className="lg:max-w-2xl">
                    <h2 className="text-base font-semibold leading-7 text-ultramarineBlue">
                      Style more, think less
                    </h2>
                    <p className="mt-2 text-4xl font-bold tracking-tight text-gray-800 dark:text-gray-100 sm:text-6xl">
                      Outfit Generator
                    </p>
                    <p className="mt-6 text-xl leading-8 text-gray-600 dark:text-gray-200">
                      Discover new outfit combinations and save your favorites
                      with our outfit generator that&apos;s tailored to your
                      unique style.
                    </p>
                    <dl className="mt-10 max-w-xl space-y-8 text-base leading-7 text-gray-600 dark:text-gray-200 lg:max-w-none">
                      {outfitGeneratorFeatures.map((feature) => (
                        <div key={feature.name} className="relative pl-9">
                          <dt className="inline font-semibold text-gray-800 dark:text-gray-100">
                            <feature.icon
                              className="absolute left-1 top-1 h-5 w-5 text-ultramarineBlue"
                              aria-hidden="true"
                            />
                            {feature.name}
                          </dt>{" "}
                          <dd className="inline">{feature.description}</dd>
                        </div>
                      ))}
                    </dl>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section id="pricing" className="py-24">
          <h2 className="text-4xl font-bold  mb-8 sm:text-6xl">Pricing</h2>
          <div className=" py-24 sm:py-20">
            <div className="mx-auto max-w-7xl px-6 lg:px-8">
              <div className="mx-auto max-w-2xl sm:text-center">
                <h2 className="text-4xl font-bold tracking-tight text-gray-800 dark:text-gray-100 sm:text-4xl">
                  Simple no-tricks pricing
                </h2>
                <p className="mt-6 text-xl leading-8 text-gray-600 dark:text-gray-200">
                  We believe in being completely transparent with our users so
                  we provided straight forward pricing plan with no hidden fees.
                </p>
              </div>
              <div className="mx-auto mt-16 max-w-2xl rounded-4xl border-2 rounded-xl sm:mt-20 lg:mx-0 lg:flex lg:max-w-none">
                <div className="p-8 sm:p-10 lg:flex-auto">
                  <h3 className="text-2xl font-bold tracking-tight text-gray-800 dark:text-gray-100">
                    Basic Plan
                  </h3>
                  <p className="mt-6 text-base leading-7 text-gray-600 dark:text-gray-200">
                    A simple plan to get you to be able express yourself sooner
                    rather than later
                  </p>
                  <div className="mt-10 flex items-center gap-x-4">
                    <h4 className="flex-none text-sm font-semibold leading-6 text-ultramarineBlue">
                      What’s included
                    </h4>
                    <div className="h-px flex-auto bg-gray-100" />
                  </div>
                  <ul className="mt-8 grid grid-cols-1 gap-4 text-sm leading-6 text-gray-600 dark:text-gray-200 sm:grid-cols-2 sm:gap-6">
                    {includedFeatures.map((feature) => (
                      <li key={feature} className="flex gap-x-3">
                        <CheckIcon
                          className="h-6 w-5 flex-none text-ultramarineBlue"
                          aria-hidden="true"
                        />
                        {feature}
                      </li>
                    ))}
                  </ul>
                </div>
                <div className="-mt-2 p-2 lg:mt-0 lg:w-full lg:max-w-md lg:flex-shrink-0">
                  <div className="rounded-2xl py-10 text-center ring-1 ring-inset ring-gray-900/5 lg:flex lg:flex-col lg:justify-center lg:py-16">
                    <div className="mx-auto max-w-xs px-8">
                      <p className="mt-6 flex items-baseline justify-center gap-x-2">
                        <span className="text-5xl font-bold tracking-tight text-gray-800 dark:text-gray-100">
                          FREE
                        </span>
                      </p>
                      <Link
                        to="/register"
                        className="mt-10 block w-full rounded-md bg-ultramarineBlue px-3 py-2 text-center text-sm font-semibold text-white shadow-sm hover:bg-blue-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-ultramarineBlue"
                      >
                        Get Started
                      </Link>
                    </div>
                  </div>
                </div>
              </div>
              <div className="mx-auto mt-16 max-w-2xl rounded-4xl border-2 rounded-xl sm:mt-20 lg:mx-0 lg:flex lg:max-w-none">
                <div className="p-8 sm:p-10 lg:flex-auto">
                  <h3 className="text-2xl font-bold tracking-tight text-gray-800 dark:text-gray-100">
                    Premium Plan
                  </h3>
                  <p className="mt-6 text-base leading-7 text-gray-600 dark:text-gray-200">
                    Basic plan not enough? Upgrade to premium to get unlimited
                    access to all our features and priority support
                  </p>
                  <div className="mt-10 flex items-center gap-x-4">
                    <h4 className="flex-none text-sm font-semibold leading-6 text-ultramarineBlue">
                      What’s included
                    </h4>
                    <div className="h-px flex-auto bg-gray-100" />
                  </div>
                  <ul className="mt-8 grid grid-cols-1 gap-4 text-sm leading-6 text-gray-600 dark:text-gray-200 sm:grid-cols-2 sm:gap-6">
                    {premiumFeatures.map((feature) => (
                      <li key={feature} className="flex gap-x-3">
                        <CheckIcon
                          className="h-6 w-5 flex-none text-ultramarineBlue"
                          aria-hidden="true"
                        />
                        {feature}
                      </li>
                    ))}
                  </ul>
                </div>
                <div className="-mt-2 p-2 lg:mt-0 lg:w-full lg:max-w-md lg:flex-shrink-0">
                  <div className="rounded-2xl py-10 text-center ring-1 ring-inset ring-gray-900/5 lg:flex lg:flex-col lg:justify-center lg:py-16">
                    <div className="mx-auto max-w-xs px-8">
                      <p className="text-base font-semibold text-gray-600 dark:text-gray-200">
                        Per Month
                      </p>
                      <p className="mt-6 flex items-baseline justify-center gap-x-2">
                        <span className="text-5xl font-bold tracking-tight text-gray-800 dark:text-gray-100">
                          $7.99
                        </span>
                        <span className="text-sm font-semibold leading-6 tracking-wide text-gray-600 dark:text-gray-200">
                          USD
                        </span>
                      </p>
                      <a
                        href="/pricing"
                        className="mt-10 block w-full rounded-md bg-ultramarineBlue px-3 py-2 text-center text-sm font-semibold text-white shadow-sm hover:bg-blue-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-ultramarineBlue "
                      >
                        Upgrade Now
                      </a>
                      <p className="mt-6 text-xs leading-5 text-gray-600 dark:text-gray-200">
                        Invoices and receipts available for easy company
                        reimbursement
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section id="FAQ" className=" mb-48">
          <h2 className="text-4xl font-bold  mb-8">FAQ</h2>
          {faq.map((section, i) => (
            <div key={i} className="mb-4 pl-10 max-w-5xl mx-auto">
              <h3 className="text-xl font-bold mb-2">{section.question}</h3>

              <p className="text-slategrey ">{section.answer}</p>
            </div>
          ))}
        </section>
      </main>
    </div>
  );
}
